### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by ssabug** [Mrugalla/Manta#4]
Hi,

I tried to build Manta on fedora linux but the compilation failed.

I modified the Makefile JUCE_CPPFLAGS adding "-FPERMISSIVE=1" .

**Source/audio/Manta.h** 

replaced `lane` by `const_cast <float**>(lane)` on lines 235,247,250,256,259

**Source/audio/DryWetMix.cpp** 

 ` dryBuf.getArrayOfWritePointers() ` by `  const_cast <float**>(dryBuf.getArrayOfWritePointers()) ` on lines 52,86 

**Source/audio/Oversampling.cpp**

 `auto samplesUp = const_cast <float**>(buffer.getArrayOfWritePointers()); ` line 269,287
`const auto samplesUpConst = const_cast <const float**>(samplesUp);` line 288
`const auto samplesIn =const_cast <float**>( inputBuffer.getArrayOfReadPointers());` line 270

**Source/audio/PitchGlitcher.cpp**

const_cast <float**>(audioBuffer.getArrayOfWritePointers()) line 214

**Source/Processor.cpp**

`auto samples = const_cast <float**>(mainBuffer.getArrayOfWritePointers());` line 176
`const auto constSamples = const_cast <const float**>(mainBuffer.getArrayOfReadPointers()); `line 177
`const auto constSamples = const_cast <const float**>(mainBuffer.getArrayOfReadPointers())` line 266
`const auto samples = const_cast <float**>(mainBuffer.getArrayOfWritePointers()); ` line 265
`const_cast <float**>(resampledMainBuf.getArrayOfWritePointers()), ` line 344

This way, standalone and vst3 builds, lv2 generates juce assertion failed errors.

The plugin works in bitwig on fedora linux. Thank you for sharing your work.

**Comment by Mrugalla** [comment]
yep. A while ago JUCE changed the return type of getArrayOfWritePointers and getArrayOfReadPointers from float** to float* const* which since then made it hard for people to just build and run older JUCE projects. Feel free to send a pull request with those changes if you want to. Also if you gave me your linux build I'd add it to the release section

**Comment by therealfumbles** [comment]
With a combination of find and sed I replaced every instance of float** with float* const* in all the .h and .cpp files and it compiled without any warnings or errors with JUCE 7.0.11 on debian.

It seems to work fine. I'm just wondering if a blanket replace like that would alter how the plugin behaves? 

I tried building it with 7.0.2 to avoid making any code changes but it failed at the end with missing operands for mkdir and cp. It was having trouble building the plugin bundles for some reason. In any case, 7.0.2 is buggy for LV2 which is my preferred format right now.

**Comment by nvssynthesis** [comment]
This issue is not Linux specific. Passing float*const* to a function that takes in float** should not be allowed on any compiler. `const_cast`ing is a dangerous, not recommended solution. I have just fixed this issue as commented above and am submitting a pull request.
